{
 "title": "SABD queries",
 "time": { "from": "2020-11-20T14:42:48.000Z", "to": "2024-01-09T18:51:32.000Z" },
 "panels": [
  {
   "title": "Q2 - Italy, carbon intensity",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Q2\")\r\n  |> range(start: 2021-01-01)\r\n  |> filter(fn: (r) => r._field == \"carbon_mean\")"
    }
   ]
  },
  {
   "title": "Q2 - Italy, CFE%",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"Q2\")\r\n  |> range(start: 2021-01-01)\r\n  |> filter(fn: (r) => r._field == \"cfe_mean\")"
    }
   ]
  },
  {
   "title": "Q2 - Italy, Carbon intensity & CFE%",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"Q2\")\r\n  |> range(start: 2021-01-01)"
    }
   ]
  },
  {
   "title": "Q1 - Italy, Carbon Intensity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "query": "from(bucket: \"Q1\")\r\n  |> range(start: 2020-01-01)\r\n  |> filter(fn: (r) => r._measurement == \"carbon_data\")\r\n  |> filter(fn: (r) => r.zone_id == \"IT\")\r\n  |> filter(fn: (r) => r._field == \"carbon_mean\")\r\n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)\r\n  |> yield(name: \"agg\")\r\n"
    },
    {
     "query": "from(bucket: \"Q1\")\r\n  |> range(start: 2020-01-01)\r\n  |> filter(fn: (r) => r._measurement == \"carbon_data\")\r\n  |> filter(fn: (r) => r.zone_id == \"IT\")\r\n  |> filter(fn: (r) => r._field == \"carbon_min\")\r\n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)\r\n  |> yield(name: \"agg\")\r\n"
    },
    {
     "query": "from(bucket: \"Q1\")\r\n  |> range(start: 2020-01-01)\r\n  |> filter(fn: (r) => r._measurement == \"carbon_data\")\r\n  |> filter(fn: (r) => r.zone_id == \"IT\")\r\n  |> filter(fn: (r) => r._field == \"carbon_max\")\r\n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)\r\n  |> yield(name: \"agg\")\r\n"
    }
   ]
  },
  {
   "title": "Q1 - Sweden, Carbon Intensity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "query": "from(bucket: \"Q1\")\r\n  |> range(start: 2020-01-01)\r\n  |> filter(fn: (r) => r._measurement == \"carbon_data\")\r\n  |> filter(fn: (r) => r.zone_id == \"SE\")\r\n  |> filter(fn: (r) => r._field == \"carbon_mean\")\r\n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)\r\n  |> yield(name: \"agg\")\r\n"
    },
    {
     "query": "from(bucket: \"Q1\")\r\n  |> range(start: 2020-01-01)\r\n  |> filter(fn: (r) => r._measurement == \"carbon_data\")\r\n  |> filter(fn: (r) => r.zone_id == \"SE\")\r\n  |> filter(fn: (r) => r._field == \"carbon_min\")\r\n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)\r\n  |> yield(name: \"agg\")\r\n"
    },
    {
     "query": "from(bucket: \"Q1\")\r\n  |> range(start: 2020-01-01)\r\n  |> filter(fn: (r) => r._measurement == \"carbon_data\")\r\n  |> filter(fn: (r) => r.zone_id == \"SE\")\r\n  |> filter(fn: (r) => r._field == \"carbon_max\")\r\n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)\r\n  |> yield(name: \"agg\")\r\n"
    }
   ]
  },
  {
   "title": "Q1 - Italy, CFE%",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "query": "from(bucket: \"Q1\")\r\n  |> range(start: 2020-01-01)\r\n  |> filter(fn: (r) => r._measurement == \"carbon_data\")\r\n  |> filter(fn: (r) => r.zone_id == \"IT\")\r\n  |> filter(fn: (r) => r._field == \"cfe_mean\")\r\n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)\r\n  |> yield(name: \"agg\")\r\n"
    },
    {
     "query": "from(bucket: \"Q1\")\r\n  |> range(start: 2020-01-01)\r\n  |> filter(fn: (r) => r._measurement == \"carbon_data\")\r\n  |> filter(fn: (r) => r.zone_id == \"IT\")\r\n  |> filter(fn: (r) => r._field == \"cfe_min\")\r\n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)\r\n  |> yield(name: \"agg\")\r\n"
    },
    {
     "query": "from(bucket: \"Q1\")\r\n  |> range(start: 2020-01-01)\r\n  |> filter(fn: (r) => r._measurement == \"carbon_data\")\r\n  |> filter(fn: (r) => r.zone_id == \"IT\")\r\n  |> filter(fn: (r) => r._field == \"cfe_max\")\r\n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)\r\n  |> yield(name: \"agg\")\r\n"
    }
   ]
  },
  {
   "title": "Q1 - Sweden, CFE%",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "query": "from(bucket: \"Q1\")\r\n  |> range(start: 2020-01-01)\r\n  |> filter(fn: (r) => r._measurement == \"carbon_data\")\r\n  |> filter(fn: (r) => r.zone_id == \"SE\")\r\n  |> filter(fn: (r) => r._field == \"cfe_mean\")\r\n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)\r\n  |> yield(name: \"agg\")\r\n"
    },
    {
     "query": "from(bucket: \"Q1\")\r\n  |> range(start: 2020-01-01)\r\n  |> filter(fn: (r) => r._measurement == \"carbon_data\")\r\n  |> filter(fn: (r) => r.zone_id == \"SE\")\r\n  |> filter(fn: (r) => r._field == \"cfe_min\")\r\n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)\r\n  |> yield(name: \"agg\")\r\n"
    },
    {
     "query": "from(bucket: \"Q1\")\r\n  |> range(start: 2020-01-01)\r\n  |> filter(fn: (r) => r._measurement == \"carbon_data\")\r\n  |> filter(fn: (r) => r.zone_id == \"SE\")\r\n  |> filter(fn: (r) => r._field == \"cfe_max\")\r\n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)\r\n  |> yield(name: \"agg\")\r\n"
    }
   ]
  },
  {
   "title": "Q1 - Italy vs Sweden, Carbon Intensity",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "query": "from(bucket: \"Q1\")\r\n  |> range(start: 2020-01-01)\r\n  |> filter(fn: (r) => r._measurement == \"carbon_data\")\r\n  |> filter(fn: (r) => r.zone_id == \"IT\" or r.zone_id == \"SE\")\r\n  |> filter(fn: (r) => r._field == \"carbon_mean\" or r._field == \"carbon_min\" or r._field == \"carbon_max\")\r\n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)\r\n  |> yield(name: \"agg\")\r\n"
    }
   ]
  },
  {
   "title": "Q1 - Italy vs Sweden,  CFE%",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "query": "from(bucket: \"Q1\")\r\n  |> range(start: 2020-01-01)\r\n  |> filter(fn: (r) => r._measurement == \"carbon_data\")\r\n  |> filter(fn: (r) => r.zone_id == \"IT\" or r.zone_id == \"SE\")\r\n  |> filter(fn: (r) => r._field == \"cfe_mean\" or r._field == \"cfe_min\" or r._field == \"cfe_max\")\r\n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)\r\n  |> yield(name: \"agg\")\r\n"
    }
   ]
  }
 ]
}